### ISSUE TITLE
Issue with integer comparison in switch

### ISSUE THREAD

**Issue by tinypocket** [ady624/webCoRE#21] opened 2017-07-27 05:33 UTC
This stopped working after a recent update/publish.  You can see in the logs & the screenshot that there is an apparent bug when comparing integers: "Comparison (integer) 1 is (integer) 1 = false (3ms)"
![image](https://user-images.githubusercontent.com/9200698/28655692-566fe9a2-7252-11e7-92ee-79b3720ae8e2.png)

Which refers to the switch statement below:

![image](https://user-images.githubusercontent.com/9200698/28655618-dcfd8584-7251-11e7-8ffc-786631926a43.png)

**Comment by ady624** [comment] 2017-08-12 12:38
I think this has been fixed in a previous release - could you please retest?

**Comment by tinypocket** [comment] 2017-08-12 16:39
Still repros:
![image](https://user-images.githubusercontent.com/9200698/29242385-7a0127e0-7f41-11e7-8133-34c67590fbcd.png)

I logged the EventDeviceIndex also. For some reason the current EventDeviceIndex is 49 and 50 instead of 1 and 2 respectively. 
![image](https://user-images.githubusercontent.com/9200698/29242395-a69dcf10-7f41-11e7-83a1-7ae31627f08f.png)
![image](https://user-images.githubusercontent.com/9200698/29242399-b40549f8-7f41-11e7-8c6d-4ce930eb18d8.png)

**Comment by ady624** [comment] 2017-08-14 23:58
Ok, the issue is with the DTH and there is also an issue with webCoRE. 49 is ASCII code for 1. 50 means 2. So there are two issues causing this:

1. DTH sends the character “1” instead of the number 1
2. webCoRE does not correctly parse the switch value as integer (though it suggests it is comparing it as such)

I can fix #2 and that will inherently fix the problem - ie accepting both strings and integers

**Comment by tinypocket** [comment] 2017-08-20 19:30
Thanks for figuring it out! I changed the DTH to send the number 1 instead of the string and it works!

**Closed** 2017-10-27 01:50 UTC
